#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-cppy
Version  : 1.2.0
Release  : 4
URL      : https://files.pythonhosted.org/packages/e0/94/3cca7fccecf9b63219f3bf8f08af719f6d3ab06c4acdcc9372a15a12b593/cppy-1.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/e0/94/3cca7fccecf9b63219f3bf8f08af719f6d3ab06c4acdcc9372a15a12b593/cppy-1.2.0.tar.gz
Summary  : C++ headers for C extension development
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-cppy-data = %{version}-%{release}
Requires: pypi-cppy-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : pypi(setuptools)
BuildRequires : pypi(setuptools_scm)
BuildRequires : pypi(wheel)

%description
Cppy
====
.. image:: https://github.com/nucleic/cppy/actions/workflows/ci.yml/badge.svg
:target: https://github.com/nucleic/cppy/actions/workflows/ci.yml

%package data
Summary: data components for the pypi-cppy package.
Group: Data

%description data
data components for the pypi-cppy package.


%package dev
Summary: dev components for the pypi-cppy package.
Group: Development
Requires: pypi-cppy-data = %{version}-%{release}
Provides: pypi-cppy-devel = %{version}-%{release}
Requires: pypi-cppy = %{version}-%{release}

%description dev
dev components for the pypi-cppy package.


%package license
Summary: license components for the pypi-cppy package.
Group: Default

%description license
license components for the pypi-cppy package.


%prep
%setup -q -n cppy-1.2.0
cd %{_builddir}/cppy-1.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1647014082
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1647014082
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-cppy
cp %{_builddir}/cppy-1.2.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-cppy/aaeb6aef24b11a94de50d8e9b2d6d1728c25a0e4
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/cppy/cmake/cppyConfig.cmake
/usr/share/cppy/cmake/cppyConfigVersion.cmake
/usr/share/cppy/cmake/cppyTargets.cmake

%files dev
%defattr(-,root,root,-)
/usr/include/cppy/cppy.h
/usr/include/cppy/defines.h
/usr/include/cppy/errors.h
/usr/include/cppy/ptr.h

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-cppy/aaeb6aef24b11a94de50d8e9b2d6d1728c25a0e4
